### ISSUE TITLE
导出export失败

### ISSUE THREAD

**Issue by kooriookami** [d2-projects/vue-table-export#13]
![image](https://user-images.githubusercontent.com/38392315/100701604-ee5ea800-33da-11eb-8866-36c10cb86d77.png)

**Comment by FairyEver** [comment]
https://d2.pub/d2-admin/preview/#/demo/plugins/export/table 这里有例子，安装的是最新版本的

**Comment by kooriookami** [comment]
> https://d2.pub/d2-admin/preview/#/demo/plugins/export/table 这里有例子，安装的是最新版本的

我找到问题了，最新版的配置项有个问题，一定要加上`merges: []`，否则会报错。
