### ISSUE TITLE
【Bug】缺少merges: []导致excel导出出错

### ISSUE THREAD

**Issue by kooriookami** [d2-projects/vue-table-export#14]
#12 #13 
配置项中不写`merges: []`，就会报错。
![image](https://user-images.githubusercontent.com/38392315/101111904-26eac580-3617-11eb-8c85-fe475ab701f1.png)

@FairyEver

**Comment by qxchen6** [comment]
还好看见了你这个issue, 不然我不知道又要花多久时间去搜到底为啥报错

**Comment by FairyEver** [comment]
fixed https://github.com/d2-projects/vue-table-export/releases/tag/v1.1.3

更新版本到 1.1.3
